### ISSUE TITLE
lookup and cross-referenced application permissions

### ISSUE THREAD

**Issue by jmfoucher** [icoxfog417/pykintone#36]
Hello,

when trying to create a record in an application (A) with a lookup field to another application (B), it always ended up with a GAIA_LO04 error code ('フィールド「fieldA」の値「fieldAvalue」が、ルックアップの参照先のフィールドにないか、また はアプリやフィールドの閲覧権限がありません。' ). The applications permission and fields permissions were checked several times and were fine.
After checking this [article](https://developer.cybozu.io/hc/ja/articles/360035992312), I modified yaml file like this :
```
apps:
    appA:
        id: XX
        token: tokenA,tokenB
    appB:
        id: XX
        token: tokenB
```
It works now but having tokenB in appA's token string makes it difficult to read and understand that appA needs appB permission as well.

Is there another nicer way to do this either in yaml file or in python?
